import{A as c,a as l,S as d,N as u,P as f,K as p,b}from"./assets/vendor-DJ1WHZIc.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();new c(".faq-list",{duration:400,showMultiple:!1});const m="https://wedding-photographer.b.goit.study/api";async function w(){return(await l.get(`${m}/feedbacks`)).data}const i=document.querySelector(".js-scroll-up");i?(window.addEventListener("scroll",()=>{window.scrollY>300?i.classList.add("is-visible"):i.classList.remove("is-visible")}),i.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})})):console.warn("Кнопку Scroll Up не знайдено на сторінці.");async function y(){const o=document.querySelector(".feedbacks-list");if(o)try{const a=(await w()).feedbacks;o.innerHTML=a.map(({name:r,descr:e})=>`
        <li class="feedbacks-card swiper-slide">
          <blockquote class="feedbacks-quote">
            <p class="feedbacks-comment">"${e}"</p>
            <cite class="feedbacks-author">${r}</cite>
          </blockquote>
        </li>
      `).join(""),g()}catch(s){console.error("Failed to load feedbacks:",s)}}function g(){new d(".feedbacks-slider",{modules:[u,f,p,b],slidesPerView:"auto",spaceBetween:24,keyboard:{enabled:!0,onlyInViewport:!0},a11y:!0,navigation:{nextEl:".feedbacks-btn-next",prevEl:".feedbacks-btn-prev",disabledClass:"feedbacks-btn-disabled"},pagination:{el:".feedbacks-pagination",clickable:!0}})}y();
//# sourceMappingURL=index.js.map
